theme: jekyll-theme-minimal
title: Matthew Martin | Portfolio
description: Computer scientist & biologist. Portfolio showcasing projects, research, and skills.
author: Matthew Martin
url: "https://matthewmartin117.github.io"
baseurl: ""
markdown: kramdown
